name: Build and push coeqwal-etl to ECR

on:
  push:
    paths:
      - 'etl/coeqwal-etl/**'
    branches:
      - dev  # change to main when ready
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual build'
        required: false
        default: 'Manual rebuild'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Checks out repository code into the GitHub Actions runner

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # Configures the AWS CLI with the necessary credentials (secrets)
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 # Logs in to Amazon ECR

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd etl/coeqwal-etl

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG